# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_app',
            new_name='first_name',
        ),
    ]
